#!/usr/bin/env python3
from __future__ import annotations

import csv
import re
import unicodedata
from collections import OrderedDict
from pathlib import Path

from ruaccent import load_accentor

ROOT = Path(__file__).resolve().parent.parent
THEME_BLOCKS_PATH = ROOT / "app" / "src" / "main" / "assets" / "theme_blocks_seed.csv"
HEADER = ["block", "russian", "transcription", "english", "translations", "examples"]

CYRILLIC_TO_LATIN = {
    "а": "a",
    "б": "b",
    "в": "v",
    "г": "g",
    "д": "d",
    "е": "ye",
    "ё": "yo",
    "ж": "zh",
    "з": "z",
    "и": "i",
    "й": "y",
    "к": "k",
    "л": "l",
    "м": "m",
    "н": "n",
    "о": "o",
    "п": "p",
    "р": "r",
    "с": "s",
    "т": "t",
    "у": "u",
    "ф": "f",
    "х": "kh",
    "ц": "ts",
    "ч": "ch",
    "ш": "sh",
    "щ": "shch",
    "ъ": "",
    "ы": "y",
    "ь": "",
    "э": "e",
    "ю": "yu",
    "я": "ya",
}
ACCENT_CHAR = "\u0301"
WORD_TOKEN_PATTERN = re.compile(r"[А-Яа-яЁё-]+")
MANUAL_ACCENTS = {
    "восемь": "во́семь",
    "девяносто": "девяно́сто",
    "двести": "две́сти",
    "четыреста": "четы́реста",
    "четвертый": "четвёртый",
    "первый": "пе́рвый",
    "второй": "второ́й",
    "третий": "тре́тий",
    "пятый": "пя́тый",
    "шестой": "шесто́й",
    "седьмой": "седьмо́й",
    "восьмой": "восьмо́й",
    "девятый": "девя́тый",
    "десятый": "деся́тый",
    "число": "число́",
    "номер": "но́мер",
    "процент": "проце́нт",
    "количество": "коли́чество",
    "четверг": "че́тверг",
    "четверть часа": "че́тверть часа́",
    "утро": "у́тро",
    "вечер": "ве́чер",
    "день": "день",
    "время": "вре́мя",
    "неделя": "неде́ля",
    "сегодня": "сего́дня",
    "завтра": "за́втра",
    "рано": "ра́но",
    "поздно": "по́здно",
    "часто": "ча́сто",
    "редко": "ре́дко",
    "быстро": "бы́стро",
    "медленно": "ме́дленно",
    "правильно": "пра́вильно",
    "интересно": "интере́сно",
    "серьезно": "серьёзно",
    "грипп": "грипп",
    "хирург": "хиру́рг",
    "автокресло": "автокре́сло",
}


def strip_accents(text: str) -> str:
    return "".join(
        ch for ch in unicodedata.normalize("NFD", text)
        if unicodedata.category(ch) != "Mn"
    )


def transliterate(text: str) -> str:
    plain = strip_accents(text.lower())
    result: list[str] = []
    for char in plain:
        result.append(CYRILLIC_TO_LATIN.get(char, char))
    return f"/{''.join(result)}/"


def safe_accent_word(word: str, accentor) -> str:
    accented = accentor.put_accent(word).replace("'", ACCENT_CHAR).strip()
    if strip_accents(accented).lower() == word.lower():
        return accented
    return word


def safe_accent_text(text: str, accentor) -> str:
    if text in MANUAL_ACCENTS:
        return MANUAL_ACCENTS[text]

    def replace(match: re.Match[str]) -> str:
        token = match.group(0)
        if token in MANUAL_ACCENTS:
            return MANUAL_ACCENTS[token]
        return safe_accent_word(token, accentor)

    return WORD_TOKEN_PATTERN.sub(replace, text)


def build_examples(word: str) -> str:
    return f'Это "{word}". | Я учу слово "{word}".'


def build_rows(block_id: str, terms: list[tuple[str, str]], accentor) -> list[list[str]]:
    rows: list[list[str]] = []
    for russian, english in terms:
        accented = safe_accent_text(russian, accentor)
        rows.append(
            [
                block_id,
                accented,
                transliterate(accented),
                english,
                english,
                build_examples(accented),
            ]
        )
    return rows


BLOCKS: "OrderedDict[str, list[tuple[str, str]]]" = OrderedDict(
    [
        (
            "professions_40",
            [
                ("врач", "doctor"),
                ("учитель", "teacher"),
                ("преподаватель", "lecturer"),
                ("инженер", "engineer"),
                ("программист", "programmer"),
                ("разработчик", "developer"),
                ("дизайнер", "designer"),
                ("архитектор", "architect"),
                ("строитель", "builder"),
                ("водитель", "driver"),
                ("повар", "cook"),
                ("кондитер", "pastry chef"),
                ("официант", "waiter"),
                ("продавец", "salesperson"),
                ("менеджер", "manager"),
                ("директор", "director"),
                ("бухгалтер", "accountant"),
                ("экономист", "economist"),
                ("юрист", "lawyer"),
                ("адвокат", "attorney"),
                ("переводчик", "translator"),
                ("журналист", "journalist"),
                ("редактор", "editor"),
                ("писатель", "writer"),
                ("актер", "actor"),
                ("актриса", "actress"),
                ("певец", "singer"),
                ("музыкант", "musician"),
                ("художник", "artist"),
                ("фотограф", "photographer"),
                ("парикмахер", "hairdresser"),
                ("визажист", "makeup artist"),
                ("косметолог", "beautician"),
                ("медсестра", "nurse"),
                ("стоматолог", "dentist"),
                ("хирург", "surgeon"),
                ("педиатр", "pediatrician"),
                ("фармацевт", "pharmacist"),
                ("ветеринар", "veterinarian"),
                ("пожарный", "firefighter"),
                ("полицейский", "police officer"),
                ("спасатель", "rescuer"),
                ("пилот", "pilot"),
                ("стюардесса", "flight attendant"),
                ("машинист", "train driver"),
                ("механик", "mechanic"),
                ("электрик", "electrician"),
                ("сантехник", "plumber"),
                ("сварщик", "welder"),
                ("токарь", "turner"),
                ("слесарь", "fitter"),
                ("фермер", "farmer"),
                ("агроном", "agronomist"),
                ("садовник", "gardener"),
                ("почтальон", "mail carrier"),
                ("курьер", "courier"),
                ("бариста", "barista"),
                ("кассир", "cashier"),
                ("охранник", "security guard"),
                ("няня", "nanny"),
                ("воспитатель", "educator"),
                ("психолог", "psychologist"),
                ("социолог", "sociologist"),
                ("ученый", "scientist"),
                ("химик", "chemist"),
                ("физик", "physicist"),
                ("биолог", "biologist"),
                ("геолог", "geologist"),
                ("историк", "historian"),
                ("библиотекарь", "librarian"),
                ("секретарь", "secretary"),
                ("администратор", "administrator"),
                ("консультант", "consultant"),
                ("маркетолог", "marketer"),
                ("аналитик", "analyst"),
                ("тестировщик", "tester"),
                ("системный администратор", "system administrator"),
                ("оператор", "operator"),
                ("логист", "logistician"),
                ("таможенник", "customs officer"),
                ("военный", "soldier"),
                ("моряк", "sailor"),
                ("рыбак", "fisherman"),
                ("шахтер", "miner"),
                ("швея", "seamstress"),
                ("портной", "tailor"),
                ("сапожник", "shoemaker"),
                ("ювелир", "jeweler"),
                ("нотариус", "notary"),
                ("судья", "judge"),
                ("прокурор", "prosecutor"),
                ("депутат", "deputy"),
                ("дипломат", "diplomat"),
                ("гид", "tour guide"),
                ("тренер", "coach"),
                ("массажист", "massage therapist"),
                ("риелтор", "realtor"),
                ("флорист", "florist"),
                ("аниматор", "animator"),
                ("уборщик", "cleaner"),
            ],
        ),
        (
            "clothes_accessories_100",
            [
                ("футболка", "T-shirt"),
                ("рубашка", "shirt"),
                ("майка", "tank top"),
                ("кофта", "sweater"),
                ("свитер", "jumper"),
                ("толстовка", "hoodie"),
                ("кардиган", "cardigan"),
                ("пиджак", "blazer"),
                ("костюм", "suit"),
                ("жилет", "vest"),
                ("куртка", "jacket"),
                ("пальто", "coat"),
                ("плащ", "raincoat"),
                ("ветровка", "windbreaker"),
                ("пуховик", "down jacket"),
                ("джинсы", "jeans"),
                ("брюки", "trousers"),
                ("штаны", "pants"),
                ("шорты", "shorts"),
                ("юбка", "skirt"),
                ("платье", "dress"),
                ("сарафан", "sundress"),
                ("блузка", "blouse"),
                ("топ", "top"),
                ("легинсы", "leggings"),
                ("колготки", "tights"),
                ("носки", "socks"),
                ("гольфы", "knee socks"),
                ("нижнее белье", "underwear"),
                ("трусы", "briefs"),
                ("бюстгальтер", "bra"),
                ("пижама", "pajamas"),
                ("халат", "robe"),
                ("купальник", "swimsuit"),
                ("плавки", "swim trunks"),
                ("шапка", "hat"),
                ("кепка", "cap"),
                ("панама", "sun hat"),
                ("берет", "beret"),
                ("шляпа", "hat"),
                ("шарф", "scarf"),
                ("платок", "headscarf"),
                ("перчатки", "gloves"),
                ("варежки", "mittens"),
                ("ремень", "belt"),
                ("галстук", "tie"),
                ("бабочка", "bow tie"),
                ("подтяжки", "suspenders"),
                ("сумка", "bag"),
                ("рюкзак", "backpack"),
                ("клатч", "clutch"),
                ("кошелек", "wallet"),
                ("зонт", "umbrella"),
                ("очки", "glasses"),
                ("солнцезащитные очки", "sunglasses"),
                ("часы", "watch"),
                ("браслет", "bracelet"),
                ("кольцо", "ring"),
                ("серьги", "earrings"),
                ("ожерелье", "necklace"),
                ("цепочка", "chain"),
                ("брошь", "brooch"),
                ("обувь", "footwear"),
                ("кроссовки", "sneakers"),
                ("кеды", "trainers"),
                ("ботинки", "boots"),
                ("полуботинки", "shoes"),
                ("туфли", "dress shoes"),
                ("босоножки", "sandals"),
                ("сандалии", "sandals"),
                ("тапки", "slippers"),
                ("сапоги", "boots"),
                ("резиновые сапоги", "rubber boots"),
                ("каблук", "heel"),
                ("шнурки", "shoelaces"),
                ("подошва", "sole"),
                ("детская одежда", "children's clothes"),
                ("детская куртка", "children's jacket"),
                ("детская шапка", "children's hat"),
                ("детские варежки", "children's mittens"),
                ("детские ботинки", "children's boots"),
                ("детский комбинезон", "children's overalls"),
                ("мужская рубашка", "men's shirt"),
                ("мужской костюм", "men's suit"),
                ("мужские туфли", "men's shoes"),
                ("женское платье", "women's dress"),
                ("женская юбка", "women's skirt"),
                ("женская блузка", "women's blouse"),
                ("женская сумка", "women's handbag"),
                ("женские туфли", "women's shoes"),
                ("размер", "size"),
                ("примерочная", "fitting room"),
                ("молния", "zipper"),
                ("пуговица", "button"),
                ("воротник", "collar"),
                ("рукав", "sleeve"),
                ("карман", "pocket"),
                ("капюшон", "hood"),
                ("манжета", "cuff"),
                ("ткань", "fabric"),
            ],
        ),
        (
            "appearance_80",
            [
                ("внешность", "appearance"),
                ("красота", "beauty"),
                ("лицо", "face"),
                ("кожа", "skin"),
                ("волосы", "hair"),
                ("прическа", "hairstyle"),
                ("лоб", "forehead"),
                ("брови", "eyebrows"),
                ("ресницы", "eyelashes"),
                ("глаза", "eyes"),
                ("нос", "nose"),
                ("щеки", "cheeks"),
                ("губы", "lips"),
                ("зубы", "teeth"),
                ("подбородок", "chin"),
                ("улыбка", "smile"),
                ("борода", "beard"),
                ("усы", "mustache"),
                ("макияж", "makeup"),
                ("маникюр", "manicure"),
                ("красивая", "beautiful"),
                ("симпатичный", "good-looking"),
                ("привлекательный", "attractive"),
                ("милый", "cute"),
                ("обаятельный", "charming"),
                ("высокий", "tall"),
                ("невысокий", "short"),
                ("низкий", "low"),
                ("стройный", "slim"),
                ("худой", "thin"),
                ("полный", "plump"),
                ("крепкий", "strong"),
                ("широкоплечий", "broad-shouldered"),
                ("молодой", "young"),
                ("пожилой", "elderly"),
                ("взрослый", "adult"),
                ("юный", "young"),
                ("красивый", "beautiful"),
                ("ухоженный", "well-groomed"),
                ("аккуратный", "neat"),
                ("небритый", "unshaven"),
                ("лысый", "bald"),
                ("кудрявый", "curly-haired"),
                ("волнистый", "wavy"),
                ("прямые волосы", "straight hair"),
                ("светлые волосы", "blond hair"),
                ("темные волосы", "dark hair"),
                ("рыжие волосы", "red hair"),
                ("седые волосы", "gray hair"),
                ("длинные волосы", "long hair"),
                ("короткие волосы", "short hair"),
                ("карие глаза", "brown eyes"),
                ("голубые глаза", "blue eyes"),
                ("зеленые глаза", "green eyes"),
                ("серые глаза", "gray eyes"),
                ("загар", "tan"),
                ("веснушки", "freckles"),
                ("морщины", "wrinkles"),
                ("шрам", "scar"),
                ("родинка", "mole"),
                ("ухо", "ear"),
                ("шея", "neck"),
                ("плечи", "shoulders"),
                ("осанка", "posture"),
                ("рост", "height"),
                ("вес", "weight"),
                ("стиль", "style"),
                ("модный", "fashionable"),
                ("элегантный", "elegant"),
                ("спортивный", "sporty"),
                ("нежный", "gentle"),
                ("яркий", "bright"),
                ("бледный", "pale"),
                ("смуглый", "dark-skinned"),
                ("сильный", "strong"),
                ("слабый", "weak"),
                ("приятный", "pleasant"),
                ("серьезный", "serious"),
                ("добрый взгляд", "kind look"),
                ("широкая улыбка", "broad smile"),
            ],
        ),
        (
            "health_100",
            [
                ("здоровье", "health"),
                ("болезнь", "illness"),
                ("простуда", "cold"),
                ("грипп", "flu"),
                ("кашель", "cough"),
                ("насморк", "runny nose"),
                ("температура", "temperature"),
                ("жар", "fever"),
                ("озноб", "chills"),
                ("головная боль", "headache"),
                ("боль в горле", "sore throat"),
                ("зубная боль", "toothache"),
                ("боль в спине", "back pain"),
                ("боль в животе", "stomach ache"),
                ("аллергия", "allergy"),
                ("перелом", "fracture"),
                ("ушиб", "bruise"),
                ("рана", "wound"),
                ("ожог", "burn"),
                ("порез", "cut"),
                ("синяк", "bruise"),
                ("отравление", "poisoning"),
                ("инфекция", "infection"),
                ("вирус", "virus"),
                ("симптом", "symptom"),
                ("диагноз", "diagnosis"),
                ("лечение", "treatment"),
                ("операция", "operation"),
                ("укол", "injection"),
                ("прививка", "vaccination"),
                ("лекарство", "medicine"),
                ("таблетка", "tablet"),
                ("сироп", "syrup"),
                ("капли", "drops"),
                ("мазь", "ointment"),
                ("бинт", "bandage"),
                ("пластырь", "plaster"),
                ("рецепт", "prescription"),
                ("аптека", "pharmacy"),
                ("больница", "hospital"),
                ("поликлиника", "clinic"),
                ("скорая помощь", "ambulance"),
                ("палата", "ward"),
                ("регистратура", "reception desk"),
                ("анализ", "test"),
                ("рентген", "X-ray"),
                ("УЗИ", "ultrasound"),
                ("давление", "blood pressure"),
                ("пульс", "pulse"),
                ("дыхание", "breathing"),
                ("выздоровление", "recovery"),
                ("пациент", "patient"),
                ("терапевт", "general practitioner"),
                ("хирург", "surgeon"),
                ("стоматолог", "dentist"),
                ("кардиолог", "cardiologist"),
                ("невролог", "neurologist"),
                ("офтальмолог", "ophthalmologist"),
                ("дерматолог", "dermatologist"),
                ("педиатр", "pediatrician"),
                ("гинеколог", "gynecologist"),
                ("медсестра", "nurse"),
                ("санитар", "orderly"),
                ("врач", "doctor"),
                ("вызвать врача", "call a doctor"),
                ("измерить температуру", "take temperature"),
                ("пить лекарства", "take medicine"),
                ("лежать в больнице", "stay in hospital"),
                ("быть здоровым", "be healthy"),
                ("чувствовать себя лучше", "feel better"),
                ("кашлять", "to cough"),
                ("чихать", "to sneeze"),
                ("болеть", "to be ill"),
                ("лечиться", "to undergo treatment"),
                ("выздоравливать", "to recover"),
                ("осмотр", "examination"),
                ("медицинская карта", "medical record"),
                ("страховка", "insurance"),
                ("скальпель", "scalpel"),
                ("градусник", "thermometer"),
                ("маска", "mask"),
                ("перчатки", "gloves"),
                ("санитайзер", "sanitizer"),
                ("перевязка", "bandaging"),
                ("обморок", "fainting"),
                ("тошнота", "nausea"),
                ("головокружение", "dizziness"),
                ("слабость", "weakness"),
                ("аппетит", "appetite"),
                ("диета", "diet"),
                ("сон", "sleep"),
                ("бессонница", "insomnia"),
                ("стресс", "stress"),
                ("усталость", "fatigue"),
                ("травма", "injury"),
                ("реабилитация", "rehabilitation"),
                ("здоровый образ жизни", "healthy lifestyle"),
                ("витамины", "vitamins"),
                ("упражнение", "exercise"),
                ("осанка", "posture"),
            ],
        ),
        (
            "sports_60",
            [
                ("спорт", "sport"),
                ("футбол", "football"),
                ("баскетбол", "basketball"),
                ("волейбол", "volleyball"),
                ("теннис", "tennis"),
                ("настольный теннис", "table tennis"),
                ("хоккей", "hockey"),
                ("плавание", "swimming"),
                ("бег", "running"),
                ("легкая атлетика", "athletics"),
                ("гимнастика", "gymnastics"),
                ("фигурное катание", "figure skating"),
                ("лыжи", "skiing"),
                ("сноуборд", "snowboarding"),
                ("биатлон", "biathlon"),
                ("бокс", "boxing"),
                ("борьба", "wrestling"),
                ("дзюдо", "judo"),
                ("карате", "karate"),
                ("шахматы", "chess"),
                ("йога", "yoga"),
                ("фитнес", "fitness"),
                ("велоспорт", "cycling"),
                ("коньки", "skating"),
                ("серфинг", "surfing"),
                ("дайвинг", "diving"),
                ("скалолазание", "climbing"),
                ("гребля", "rowing"),
                ("гольф", "golf"),
                ("регби", "rugby"),
                ("гандбол", "handball"),
                ("бейсбол", "baseball"),
                ("конный спорт", "equestrian sport"),
                ("прыжки", "jumping"),
                ("тренировка", "training"),
                ("соревнование", "competition"),
                ("турнир", "tournament"),
                ("матч", "match"),
                ("команда", "team"),
                ("игрок", "player"),
                ("тренер", "coach"),
                ("судья", "referee"),
                ("болельщик", "fan"),
                ("стадион", "stadium"),
                ("спортзал", "gym"),
                ("площадка", "sports ground"),
                ("мяч", "ball"),
                ("ракетка", "racket"),
                ("ворота", "goal"),
                ("гол", "goal scored"),
                ("победа", "victory"),
                ("поражение", "defeat"),
                ("ничья", "draw"),
                ("медаль", "medal"),
                ("кубок", "cup"),
                ("чемпион", "champion"),
                ("рекорд", "record"),
                ("разминка", "warm-up"),
                ("силовая тренировка", "strength training"),
                ("командный спорт", "team sport"),
            ],
        ),
        (
            "home_apartment_120",
            [
                ("дом", "house"),
                ("квартира", "apartment"),
                ("подъезд", "entrance hall"),
                ("лестница", "stairs"),
                ("лифт", "elevator"),
                ("этаж", "floor"),
                ("дверь", "door"),
                ("замок", "lock"),
                ("ключ", "key"),
                ("коридор", "hallway"),
                ("прихожая", "entryway"),
                ("гостиная", "living room"),
                ("спальня", "bedroom"),
                ("детская", "children's room"),
                ("кабинет", "study"),
                ("кухня", "kitchen"),
                ("столовая", "dining room"),
                ("ванная", "bathroom"),
                ("душ", "shower"),
                ("туалет", "toilet"),
                ("балкон", "balcony"),
                ("лоджия", "loggia"),
                ("кладовка", "storage room"),
                ("подвал", "basement"),
                ("чердак", "attic"),
                ("окно", "window"),
                ("подоконник", "windowsill"),
                ("шторы", "curtains"),
                ("жалюзи", "blinds"),
                ("стена", "wall"),
                ("потолок", "ceiling"),
                ("пол", "floor"),
                ("ковер", "carpet"),
                ("лампа", "lamp"),
                ("люстра", "chandelier"),
                ("розетка", "socket"),
                ("выключатель", "switch"),
                ("отопление", "heating"),
                ("батарея", "radiator"),
                ("кондиционер", "air conditioner"),
                ("мебель", "furniture"),
                ("диван", "sofa"),
                ("кресло", "armchair"),
                ("стул", "chair"),
                ("табурет", "stool"),
                ("стол", "table"),
                ("журнальный столик", "coffee table"),
                ("шкаф", "wardrobe"),
                ("комод", "dresser"),
                ("полка", "shelf"),
                ("кровать", "bed"),
                ("матрас", "mattress"),
                ("подушка", "pillow"),
                ("одеяло", "blanket"),
                ("простыня", "sheet"),
                ("пододеяльник", "duvet cover"),
                ("наволочка", "pillowcase"),
                ("плед", "throw blanket"),
                ("зеркало", "mirror"),
                ("картина", "painting"),
                ("ваза", "vase"),
                ("часы", "clock"),
                ("телевизор", "television"),
                ("пульт", "remote control"),
                ("компьютер", "computer"),
                ("ноутбук", "laptop"),
                ("зарядка", "charger"),
                ("удлинитель", "extension cord"),
                ("интернет", "internet"),
                ("вайфай", "Wi-Fi"),
                ("холодильник", "refrigerator"),
                ("морозильник", "freezer"),
                ("плита", "stove"),
                ("духовка", "oven"),
                ("микроволновка", "microwave"),
                ("чайник", "kettle"),
                ("кофеварка", "coffee maker"),
                ("тостер", "toaster"),
                ("блендер", "blender"),
                ("посуда", "dishes"),
                ("тарелка", "plate"),
                ("миска", "bowl"),
                ("чашка", "cup"),
                ("кружка", "mug"),
                ("стакан", "glass"),
                ("вилка", "fork"),
                ("ложка", "spoon"),
                ("нож", "knife"),
                ("кастрюля", "pot"),
                ("сковорода", "frying pan"),
                ("раковина", "sink"),
                ("кран", "tap"),
                ("губка", "sponge"),
                ("полотенце", "towel"),
                ("мыло", "soap"),
                ("шампунь", "shampoo"),
                ("зубная щетка", "toothbrush"),
                ("зубная паста", "toothpaste"),
                ("стиральная машина", "washing machine"),
                ("сушилка", "dryer rack"),
                ("пылесос", "vacuum cleaner"),
                ("утюг", "iron"),
                ("гладильная доска", "ironing board"),
                ("ведро", "bucket"),
                ("швабра", "mop"),
                ("метла", "broom"),
                ("мусор", "trash"),
                ("мусорное ведро", "trash bin"),
                ("ремонт", "renovation"),
                ("обои", "wallpaper"),
                ("краска", "paint"),
                ("плитка", "tiles"),
                ("аренда", "rent"),
                ("сосед", "neighbor"),
                ("адрес", "address"),
                ("кварплата", "utility bill"),
                ("уют", "comfort"),
                ("чистота", "cleanliness"),
                ("порядок", "order"),
                ("уютный", "cozy"),
            ],
        ),
        (
            "confectionery_50",
            [
                ("кондитерская", "pastry shop"),
                ("торт", "cake"),
                ("пирожное", "pastry"),
                ("печенье", "cookies"),
                ("кекс", "muffin"),
                ("маффин", "muffin"),
                ("капкейк", "cupcake"),
                ("эклер", "eclair"),
                ("безе", "meringue"),
                ("макарон", "macaron"),
                ("рулет", "roll cake"),
                ("штрудель", "strudel"),
                ("чизкейк", "cheesecake"),
                ("брауни", "brownie"),
                ("вафля", "waffle"),
                ("пончик", "doughnut"),
                ("круассан", "croissant"),
                ("булочка", "sweet bun"),
                ("плюшка", "bun"),
                ("слойка", "puff pastry"),
                ("пирог", "pie"),
                ("тарт", "tart"),
                ("бисквит", "sponge cake"),
                ("суфле", "souffle"),
                ("мусс", "mousse"),
                ("крем", "cream"),
                ("начинка", "filling"),
                ("шоколад", "chocolate"),
                ("конфета", "candy"),
                ("карамель", "caramel"),
                ("мармелад", "jelly candy"),
                ("зефир", "marshmallow"),
                ("пастила", "fruit candy"),
                ("мороженое", "ice cream"),
                ("сорбет", "sorbet"),
                ("варенье", "jam"),
                ("джем", "jam"),
                ("мед", "honey"),
                ("сахарная пудра", "powdered sugar"),
                ("ваниль", "vanilla"),
                ("корица", "cinnamon"),
                ("ягодный торт", "berry cake"),
                ("шоколадный торт", "chocolate cake"),
                ("свадебный торт", "wedding cake"),
                ("заказать торт", "order a cake"),
                ("сладкий", "sweet"),
                ("свежая выпечка", "fresh pastries"),
                ("витрина", "display case"),
                ("десерт", "dessert"),
                ("кусок торта", "slice of cake"),
            ],
        ),
        (
            "transport_80",
            [
                ("транспорт", "transport"),
                ("машина", "car"),
                ("автомобиль", "automobile"),
                ("такси", "taxi"),
                ("автобус", "bus"),
                ("троллейбус", "trolleybus"),
                ("трамвай", "tram"),
                ("маршрутка", "minibus"),
                ("метро", "metro"),
                ("поезд", "train"),
                ("электричка", "commuter train"),
                ("вагон", "carriage"),
                ("станция", "station"),
                ("платформа", "platform"),
                ("вокзал", "terminal"),
                ("самолет", "airplane"),
                ("аэропорт", "airport"),
                ("вертолет", "helicopter"),
                ("корабль", "ship"),
                ("лодка", "boat"),
                ("паром", "ferry"),
                ("велосипед", "bicycle"),
                ("самокат", "scooter"),
                ("мотоцикл", "motorcycle"),
                ("грузовик", "truck"),
                ("фура", "lorry"),
                ("трактор", "tractor"),
                ("скорость", "speed"),
                ("дорога", "road"),
                ("улица", "street"),
                ("шоссе", "highway"),
                ("перекресток", "intersection"),
                ("светофор", "traffic light"),
                ("переход", "crosswalk"),
                ("остановка", "stop"),
                ("маршрут", "route"),
                ("билет", "ticket"),
                ("проездной", "travel pass"),
                ("расписание", "timetable"),
                ("пассажир", "passenger"),
                ("водитель", "driver"),
                ("машинист", "train driver"),
                ("пилот", "pilot"),
                ("рейс", "flight"),
                ("багаж", "luggage"),
                ("чемодан", "suitcase"),
                ("ремень безопасности", "seat belt"),
                ("автокресло", "car seat"),
                ("парковка", "parking"),
                ("пробка", "traffic jam"),
                ("авария", "accident"),
                ("штраф", "fine"),
                ("права", "driving licence"),
                ("заправка", "gas station"),
                ("бензин", "petrol"),
                ("дизель", "diesel"),
                ("колесо", "wheel"),
                ("руль", "steering wheel"),
                ("сиденье", "seat"),
                ("дверца", "door"),
                ("багажник", "trunk"),
                ("капот", "hood"),
                ("фара", "headlight"),
                ("номер", "number plate"),
                ("общественный транспорт", "public transport"),
                ("подземный переход", "underpass"),
                ("надземный переход", "overpass"),
                ("пешеход", "pedestrian"),
                ("ехать", "to go by transport"),
                ("приехать", "to arrive"),
                ("уехать", "to leave"),
                ("пересадка", "transfer"),
                ("перрон", "platform area"),
                ("вылет", "departure"),
                ("прилет", "arrival"),
                ("задержка", "delay"),
                ("удобный", "comfortable"),
                ("быстрый", "fast"),
                ("медленный", "slow"),
                ("переполненный", "crowded"),
            ],
        ),
        (
            "outdoor_recreation_60",
            [
                ("отдых на природе", "outdoor recreation"),
                ("пикник", "picnic"),
                ("шашлык", "barbecue"),
                ("мангал", "grill"),
                ("шампур", "skewer"),
                ("уголь", "charcoal"),
                ("костер", "campfire"),
                ("палатка", "tent"),
                ("спальный мешок", "sleeping bag"),
                ("рюкзак", "backpack"),
                ("коврик", "mat"),
                ("поход", "hike"),
                ("тропинка", "path"),
                ("лес", "forest"),
                ("река", "river"),
                ("озеро", "lake"),
                ("море", "sea"),
                ("пляж", "beach"),
                ("песок", "sand"),
                ("волна", "wave"),
                ("загар", "tan"),
                ("купаться", "to swim"),
                ("загорать", "to sunbathe"),
                ("плавать", "to swim"),
                ("лодка", "boat"),
                ("удочка", "fishing rod"),
                ("рыбалка", "fishing"),
                ("гриб", "mushroom"),
                ("ягода", "berry"),
                ("корзина", "basket"),
                ("раскладной стул", "folding chair"),
                ("плед", "blanket"),
                ("термос", "thermos"),
                ("холодильная сумка", "cooler bag"),
                ("сок", "juice"),
                ("вода", "water"),
                ("бутерброд", "sandwich"),
                ("сосиска", "sausage"),
                ("салат", "salad"),
                ("фрукты", "fruit"),
                ("овощи", "vegetables"),
                ("солнцезащитный крем", "sunscreen"),
                ("полотенце", "towel"),
                ("сланцы", "flip-flops"),
                ("купальник", "swimsuit"),
                ("мяч", "ball"),
                ("бадминтон", "badminton"),
                ("гамак", "hammock"),
                ("закат", "sunset"),
                ("рассвет", "sunrise"),
                ("отдыхать", "to relax"),
                ("гулять", "to walk"),
                ("жарить мясо", "grill meat"),
                ("разжечь костер", "light a fire"),
                ("ставить палатку", "pitch a tent"),
                ("собирать ягоды", "pick berries"),
                ("собирать грибы", "pick mushrooms"),
                ("чистый воздух", "fresh air"),
                ("выходной", "day off"),
                ("хорошая компания", "good company"),
            ],
        ),
        (
            "weather_50",
            [
                ("погода", "weather"),
                ("температура", "temperature"),
                ("солнце", "sun"),
                ("солнечно", "sunny"),
                ("ясно", "clear"),
                ("облачно", "cloudy"),
                ("пасмурно", "overcast"),
                ("ветер", "wind"),
                ("ветрено", "windy"),
                ("дождь", "rain"),
                ("ливень", "downpour"),
                ("морось", "drizzle"),
                ("гроза", "thunderstorm"),
                ("молния", "lightning"),
                ("гром", "thunder"),
                ("снег", "snow"),
                ("снегопад", "snowfall"),
                ("метель", "blizzard"),
                ("мороз", "frost"),
                ("холодно", "cold"),
                ("прохладно", "cool"),
                ("тепло", "warm"),
                ("жарко", "hot"),
                ("зной", "heat"),
                ("туман", "fog"),
                ("влажность", "humidity"),
                ("гололед", "ice"),
                ("лужа", "puddle"),
                ("радуга", "rainbow"),
                ("облако", "cloud"),
                ("небо", "sky"),
                ("прогноз погоды", "weather forecast"),
                ("синоптик", "weather forecaster"),
                ("циклон", "cyclone"),
                ("антициклон", "anticyclone"),
                ("заморозки", "frosts"),
                ("оттепель", "thaw"),
                ("жара", "heat"),
                ("сухо", "dry"),
                ("сыро", "damp"),
                ("давление", "pressure"),
                ("шторм", "storm"),
                ("ураган", "hurricane"),
                ("капля дождя", "raindrop"),
                ("снежинка", "snowflake"),
                ("лед", "ice"),
                ("потепление", "warming"),
                ("похолодание", "cooling"),
                ("переменная облачность", "partly cloudy"),
                ("хорошая погода", "good weather"),
            ],
        ),
        (
            "time_calendar_80",
            [
                ("время", "time"),
                ("календарь", "calendar"),
                ("дата", "date"),
                ("год", "year"),
                ("месяц", "month"),
                ("неделя", "week"),
                ("день", "day"),
                ("час", "hour"),
                ("минута", "minute"),
                ("секунда", "second"),
                ("понедельник", "Monday"),
                ("вторник", "Tuesday"),
                ("среда", "Wednesday"),
                ("четверг", "Thursday"),
                ("пятница", "Friday"),
                ("суббота", "Saturday"),
                ("воскресенье", "Sunday"),
                ("январь", "January"),
                ("февраль", "February"),
                ("март", "March"),
                ("апрель", "April"),
                ("май", "May"),
                ("июнь", "June"),
                ("июль", "July"),
                ("август", "August"),
                ("сентябрь", "September"),
                ("октябрь", "October"),
                ("ноябрь", "November"),
                ("декабрь", "December"),
                ("утро", "morning"),
                ("дневное время", "daytime"),
                ("вечер", "evening"),
                ("ночь", "night"),
                ("полдень", "noon"),
                ("полночь", "midnight"),
                ("сегодня", "today"),
                ("вчера", "yesterday"),
                ("завтра", "tomorrow"),
                ("позавчера", "the day before yesterday"),
                ("послезавтра", "the day after tomorrow"),
                ("сейчас", "now"),
                ("потом", "later"),
                ("раньше", "earlier"),
                ("скоро", "soon"),
                ("поздно", "late"),
                ("рано", "early"),
                ("часто", "often"),
                ("редко", "rarely"),
                ("иногда", "sometimes"),
                ("всегда", "always"),
                ("никогда", "never"),
                ("сезон", "season"),
                ("весна", "spring"),
                ("лето", "summer"),
                ("осень", "autumn"),
                ("зима", "winter"),
                ("будни", "weekdays"),
                ("выходные", "weekend"),
                ("праздник", "holiday"),
                ("каникулы", "vacation"),
                ("отпуск", "leave"),
                ("день рождения", "birthday"),
                ("расписание", "schedule"),
                ("встреча", "meeting"),
                ("срок", "deadline"),
                ("начало", "beginning"),
                ("конец", "end"),
                ("перерыв", "break"),
                ("пауза", "pause"),
                ("четверть часа", "quarter of an hour"),
                ("полчаса", "half an hour"),
                ("сутки", "twenty-four hours"),
                ("прошлое", "past"),
                ("настоящее", "present"),
                ("будущее", "future"),
                ("ежедневно", "daily"),
                ("еженедельно", "weekly"),
                ("ежемесячно", "monthly"),
                ("ежегодно", "yearly"),
                ("по календарю", "according to the calendar"),
            ],
        ),
        (
            "adverbs_100",
            [
                ("быстро", "quickly"),
                ("медленно", "slowly"),
                ("хорошо", "well"),
                ("плохо", "badly"),
                ("легко", "easily"),
                ("трудно", "with difficulty"),
                ("тихо", "quietly"),
                ("громко", "loudly"),
                ("далеко", "far"),
                ("близко", "near"),
                ("рядом", "nearby"),
                ("здесь", "here"),
                ("там", "there"),
                ("везде", "everywhere"),
                ("нигде", "nowhere"),
                ("внутри", "inside"),
                ("снаружи", "outside"),
                ("вверху", "upstairs"),
                ("снизу", "from below"),
                ("впереди", "ahead"),
                ("сзади", "behind"),
                ("слева", "on the left"),
                ("справа", "on the right"),
                ("вместе", "together"),
                ("отдельно", "separately"),
                ("снова", "again"),
                ("опять", "again"),
                ("уже", "already"),
                ("еще", "still"),
                ("только", "only"),
                ("почти", "almost"),
                ("совсем", "completely"),
                ("точно", "exactly"),
                ("примерно", "approximately"),
                ("специально", "on purpose"),
                ("случайно", "by accident"),
                ("внезапно", "suddenly"),
                ("постепенно", "gradually"),
                ("сразу", "immediately"),
                ("наконец", "finally"),
                ("пока", "for now"),
                ("потом", "later"),
                ("сегодня", "today"),
                ("завтра", "tomorrow"),
                ("вчера", "yesterday"),
                ("часто", "often"),
                ("редко", "rarely"),
                ("иногда", "sometimes"),
                ("обычно", "usually"),
                ("всегда", "always"),
                ("никогда", "never"),
                ("ежедневно", "daily"),
                ("еженедельно", "weekly"),
                ("дома", "at home"),
                ("наверху", "upstairs"),
                ("внизу", "downstairs"),
                ("впустую", "in vain"),
                ("вручную", "manually"),
                ("онлайн", "online"),
                ("офлайн", "offline"),
                ("долго", "for a long time"),
                ("недолго", "for a short time"),
                ("днем", "during the day"),
                ("ночью", "at night"),
                ("рано", "early"),
                ("поздно", "late"),
                ("вовремя", "on time"),
                ("своевременно", "in good time"),
                ("неожиданно", "unexpectedly"),
                ("спокойно", "calmly"),
                ("нервно", "nervously"),
                ("уверенно", "confidently"),
                ("осторожно", "carefully"),
                ("аккуратно", "neatly"),
                ("бережно", "carefully"),
                ("смело", "boldly"),
                ("честно", "honestly"),
                ("правильно", "correctly"),
                ("неправильно", "incorrectly"),
                ("отлично", "excellent"),
                ("ужасно", "terribly"),
                ("прекрасно", "wonderfully"),
                ("грустно", "sadly"),
                ("весело", "cheerfully"),
                ("серьезно", "seriously"),
                ("интересно", "interestingly"),
                ("скучно", "boringly"),
                ("полностью", "fully"),
                ("частично", "partly"),
                ("достаточно", "enough"),
                ("слишком", "too much"),
                ("особенно", "especially"),
                ("поэтому", "therefore"),
                ("возможно", "possibly"),
                ("обязательно", "definitely"),
                ("наверное", "probably"),
                ("действительно", "really"),
                ("бесплатно", "free of charge"),
                ("дорого", "expensively"),
                ("дешево", "cheaply"),
            ],
        ),
        (
            "numbers_50",
            [
                ("ноль", "zero"),
                ("один", "one"),
                ("два", "two"),
                ("три", "three"),
                ("четыре", "four"),
                ("пять", "five"),
                ("шесть", "six"),
                ("семь", "seven"),
                ("восемь", "eight"),
                ("девять", "nine"),
                ("десять", "ten"),
                ("одиннадцать", "eleven"),
                ("двенадцать", "twelve"),
                ("тринадцать", "thirteen"),
                ("четырнадцать", "fourteen"),
                ("пятнадцать", "fifteen"),
                ("шестнадцать", "sixteen"),
                ("семнадцать", "seventeen"),
                ("восемнадцать", "eighteen"),
                ("девятнадцать", "nineteen"),
                ("двадцать", "twenty"),
                ("тридцать", "thirty"),
                ("сорок", "forty"),
                ("пятьдесят", "fifty"),
                ("шестьдесят", "sixty"),
                ("семьдесят", "seventy"),
                ("восемьдесят", "eighty"),
                ("девяносто", "ninety"),
                ("сто", "hundred"),
                ("двести", "two hundred"),
                ("триста", "three hundred"),
                ("четыреста", "four hundred"),
                ("пятьсот", "five hundred"),
                ("тысяча", "thousand"),
                ("миллион", "million"),
                ("миллиард", "billion"),
                ("первый", "first"),
                ("второй", "second"),
                ("третий", "third"),
                ("четвертый", "fourth"),
                ("пятый", "fifth"),
                ("шестой", "sixth"),
                ("седьмой", "seventh"),
                ("восьмой", "eighth"),
                ("девятый", "ninth"),
                ("десятый", "tenth"),
                ("число", "number"),
                ("цифра", "digit"),
                ("номер", "number"),
                ("процент", "percent"),
            ],
        ),
        (
            "prepositions_35",
            [
                ("в", "in"),
                ("на", "on"),
                ("под", "under"),
                ("над", "above"),
                ("перед", "in front of"),
                ("за", "behind"),
                ("между", "between"),
                ("около", "near"),
                ("возле", "next to"),
                ("у", "by"),
                ("из", "from"),
                ("с", "from"),
                ("к", "to"),
                ("по", "along"),
                ("для", "for"),
                ("без", "without"),
                ("до", "until"),
                ("после", "after"),
                ("при", "in the presence of"),
                ("через", "through"),
                ("сквозь", "through"),
                ("вдоль", "along"),
                ("вокруг", "around"),
                ("мимо", "past"),
                ("напротив", "opposite"),
                ("вместо", "instead of"),
                ("кроме", "except"),
                ("среди", "among"),
                ("против", "against"),
                ("благодаря", "thanks to"),
                ("из-за", "because of"),
                ("из-под", "from under"),
                ("по поводу", "regarding"),
                ("в течение", "during"),
                ("в связи с", "in connection with"),
            ],
        ),
        (
            "pronouns_60",
            [
                ("я", "I"),
                ("меня", "me"),
                ("мне", "to me"),
                ("мной", "by me"),
                ("ты", "you"),
                ("тебя", "you"),
                ("тебе", "to you"),
                ("тобой", "by you"),
                ("он", "he"),
                ("его", "him"),
                ("ему", "to him"),
                ("им", "by him"),
                ("она", "she"),
                ("ее", "her"),
                ("ей", "to her"),
                ("ею", "by her"),
                ("оно", "it"),
                ("мы", "we"),
                ("нас", "us"),
                ("нам", "to us"),
                ("нами", "by us"),
                ("вы", "you plural"),
                ("вас", "you plural"),
                ("вам", "to you plural"),
                ("вами", "by you plural"),
                ("они", "they"),
                ("их", "them"),
                ("ими", "by them"),
                ("мой", "my"),
                ("моя", "my feminine"),
                ("мое", "my neuter"),
                ("мои", "my plural"),
                ("твой", "your"),
                ("твоя", "your feminine"),
                ("твое", "your neuter"),
                ("твои", "your plural"),
                ("наш", "our"),
                ("наша", "our feminine"),
                ("наше", "our neuter"),
                ("наши", "our plural"),
                ("ваш", "your formal"),
                ("ваша", "your formal feminine"),
                ("ваше", "your formal neuter"),
                ("ваши", "your formal plural"),
                ("этот", "this"),
                ("эта", "this feminine"),
                ("это", "this neuter"),
                ("эти", "these"),
                ("тот", "that"),
                ("та", "that feminine"),
                ("то", "that neuter"),
                ("те", "those"),
                ("себя", "oneself"),
                ("себе", "to oneself"),
                ("собой", "by oneself"),
                ("кто", "who"),
                ("что", "what"),
                ("который", "which"),
                ("никто", "nobody"),
                ("ничто", "nothing"),
            ],
        ),
    ]
)


def load_existing_rows() -> list[list[str]]:
    with THEME_BLOCKS_PATH.open("r", encoding="utf-8", newline="") as handle:
        reader = csv.reader(handle, delimiter=";")
        header = next(reader)
        if header != HEADER:
            raise SystemExit(f"Unexpected header in {THEME_BLOCKS_PATH.name}: {header!r}")
        return [row for row in reader]


def main() -> int:
    accentor = load_accentor()
    existing_rows = load_existing_rows()
    replaced_blocks = set(BLOCKS.keys())
    preserved = [row for row in existing_rows if row[0] not in replaced_blocks]

    generated: list[list[str]] = []
    for block_id, terms in BLOCKS.items():
        if len(terms) != len({russian for russian, _english in terms}):
            raise SystemExit(f"Duplicate Russian headwords in {block_id}")
        generated.extend(build_rows(block_id, terms, accentor))

    output_rows = preserved + generated
    with THEME_BLOCKS_PATH.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.writer(handle, delimiter=";", lineterminator="\n")
        writer.writerow(HEADER)
        writer.writerows(output_rows)

    for block_id, terms in BLOCKS.items():
        print(f"{block_id}: {len(terms)} rows")
    print(f"Wrote {len(output_rows)} theme rows to {THEME_BLOCKS_PATH}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
